###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mailhog:
      image: mailhog/mailhog:latest
      container_name: mywisedocker-mailhog
      ports:
        - "8025:8025"

    redis:
      image: redis:alpine
      container_name: mywisedocker-redis

    mysql:
      image: mysql:5.7
      container_name: mywisedocker-mysql
      working_dir: /application
      volumes:
        - ../www:/application
      environment:
        - MYSQL_ROOT_PASSWORD=secret
        - MYSQL_DATABASE=default
        - MYSQL_USER=mysql_user
        - MYSQL_PASSWORD=Password2021^^
      ports:
        - "3306:3306"

    webserver:
      image: nginx:alpine
      container_name: mywisedocker-webserver
      working_dir: /application
      volumes:
          - ../www:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: mywisedocker-php-fpm
      working_dir: /application
      volumes:
        - ../www:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

